name: app_frontend
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  fl_chart: ^0.68.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_search_bar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - lib/assets/3dDoctor.png
    - lib/assets/login.png
    - lib/assets/urbandoctors.gif
    - lib/assets/Note.png
    - lib/assets/forgot_password.png
